### PR TITLE
Updated urls for latest VMware and VMware Tools

### PR DESCRIPTION
**Pull request by robertapengelly**
I've updated the url and file paths for the latest vmware tools and tested the .iso and it runs and installs within a vm.

### CODE REVIEW

**Review by avighnac — APPROVED** [review]

**Comment by NikitaSavc** [comment]
You saved me! Thank you! Current version is bad, i needed this commit! 
Thank you!

**Comment by NikitaSavc** [comment]
@paolo-projects you need apply this commit, your code of gettools.py is ded

**Comment by SanabriaDDi** [comment]
Thank's @robertapengelly this commit works!

**Comment by paolo-projects** [comment]
Recently I've been a lot involved with my job, I hope to review and merge this commit by this evening

**Comment by rowdyruppert** [comment]
Which vmware do you use? Because I dowloaded vmware 14 Player, dowloaded 'release-python-embedded' on windows and it added darwin.iso to vmware but when I try to create new virtaul machine macOS system does not show up.

**Comment by rowdyruppert** [comment]
> I've updated the url and file paths for the latest vmware tools and tested the .iso and it runs and installs within a vm.

Which vmware do you use? Because I dowloaded vmware 14 Player, dowloaded 'release-python-embedded' on windows and it added darwin.iso to vmware but when I try to create new virtaul machine macOS system does not show up.

**Comment by gh-SAngeli** [comment]
Hi,
sorry for my message in here. Can anyone please try to answer to my post, if possible?
https://github.com/paolo-projects/auto-unlocker/discussions/108
many thanks!

**Comment by mubashirsiddique** [comment]
i have below missing for darwin iso, anybody can help =>

Traceback (most recent call last):
  File "D:\Downloads\release-python-embedded\gettools.py", line 166, in <module>
    main()
  File "D:\Downloads\release-python-embedded\gettools.py", line 148, in main
    cdszip.extract('payload/VMware Fusion.app/Contents/Library/isoimages/' + ARCH + '/darwin.iso', path=convertpath(dest + '/tools/'))
  File "zipfile.py", line 1625, in extract
  File "zipfile.py", line 1664, in _extract_member
  File "zipfile.py", line 1438, in getinfo
KeyError: "There is no item named 'payload/VMware Fusion.app/Contents/Library/isoimages/x86_x64/darwin.iso' in the archive"
File not found - darwin*.*
0 File(s) copied

**Comment by BDisp** [comment]
See #10 comments.

**Pull request merged**
