### PR TITLE
Fixed darwin.iso download errors

### PR DESCRIPTION
**Pull request by Debdut**
Fixed

-  gettools.py - Downloads happening correctly 
- lnx-install.sh - python missing, needs to be python3

### CODE REVIEW

**Comment by anpin** [comment]
Hi, thanks for your effort, but on windows download still fails with 
```
Getting VMware Tools...
Trying to get tools from the packages folder...
Retrieving Darwin tools from: http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/12.2.1/18811640/packages/com.vmware.fusion.tools.darwin.zip.tar
Tools aren't here... Be patient while I download and give a look into the core.vmware.fusion.tar file
Couldn't find tools

Extracting com.vmware.fusion.zip.tar...
Traceback (most recent call last):
  File "gettools.py", line 136, in main
    urlretrieve(urlcoretar, convertpath(dest + '/tools/com.vmware.fusion.zip.tar'), reporthook)
  File "urllib\request.py", line 247, in urlretrieve
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 641, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gettools.py", line 224, in <module>
  File "gettools.py", line 153, in main
    shutil.move(convertpath(dest + '/tools/payload/VMware Fusion.app/Contents/Library/isoimages/darwin.iso'), convertpath(dest + '/tools/darwin.iso'))
  File "tarfile.py", line 1573, in open
  File "tarfile.py", line 1638, in gzopen
  File "gzip.py", line 163, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/user/unlocker/tools/com.vmware.fusion.zip.tar'
[6128] Failed to execute script gettools
File not found - darwin*.*
0 File(s) copied
```

**Comment by Debdut** [comment]
I fixed the script for Linux, I'll give the Windows a ago and fix it if possible.

**Comment by EightB1ts** [comment]
> I fixed the script for Linux, I'll give the Windows a ago and fix it if possible.

Thanks for your time spent fixing this, your changes work fine for Windows. The issue is that win-install.bat calls upon gettools.exe, not gettools.py to pull the files. 

@anpin Make sure you have python installed on your machine before proceeding. 

You have two options:

- Modify win-install.cmd and change line `gettools.exe` to `python gettools.py`

- Rebuild gettools.exe
   1. Install pyinstaller by running this command: `pip install pyinstaller`
   2. Run win-build.cmd

**Comment by nagutabby** [comment]
@EightB1ts Thank you for letting me know! I tried the first way, and it worked fine!

**Comment by Debdut** [comment]
Windows Build fixed guys, should work now! Please report @anpin @EightB1ts @nagutabby

**Comment by Debdut** [comment]
@paolo-projects it works, please have a look and merge it asap!

**Comment by paolo-projects** [comment]
Hi Debdut,
thank you for the contribution. I can't merge your pull request as it includes an executable, and given that it's not been compiled by me I can't be responsible for it.
As for the other modifications, they look good to me except for the ARCH that is hardcoded, but I guess the patch wouldn't run anyway on arm so that's not an issue. If you could rebase to the commit with no compiled binary, and I guess also switch the bash command to (temporarily) executing the script instead of the executable it will be fine.

**Comment by Debdut** [comment]
@paolo-projects done 😄

**Pull request merged**
