### PR TITLE
Rename readme.txt to README.md

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pzhlkj6612** [comment]
Hi. Did you see the [rendered file](https://github.com/MatusModder/unlocker/blob/a28d69950d3827ebf1aebc6c0dd259329071ef43/README.md)? I don't think Markdown format is suitable for this file.

**Comment by mvjimeno** [comment]
no ..actually this is my first time to explore this app

**Comment by oliverkardos** [comment]
Can you just fix the core dump issue on Windows?

**Comment by mkitchingh** [comment]
> Can you just fix the core dump issue on Windows?

Can you supply some more details? Others aren't seeing this issue.

**Pull request closed without merging**
